### ISSUE TITLE
Can I haz new version

### ISSUE THREAD

**Issue by timbru31** [NiklasMerz/release-test#37]
when latest on npm??

**Comment by NiklasMerz** [comment]
Wont close. Do we need to adjust this? https://github.com/NiklasMerz/release-notify/blob/7d9904942416848dc74a5ec1e1bb7459a3726a57/src/main.js#L4

**Comment by timbru31** [comment]
Yeah I see, penalty is only at 5

Test editing your comment

npm release

Editing again:
When is the latest version on npm released?

**Comment by timbru31** [comment]
@NiklasMerz is the bot/are the actions supposed to run on edit of issues or comments, too?

**Comment by NiklasMerz** [comment]
No it's not. Just wanted to test that. The Action ist set to run on create.
